language: python
python:
- 2.6
- 2.7
sudo: false
services:
- redis
before_install:
- sed -i.old -e s/4.3.x/$PLONE/g buildout.cfg versions:zc.recipe.egg=
install:
- python bootstrap.py
- bin/buildout -N -t 3
script:
- bin/test
- bin/code-analysis
cache:
  directories:
  - eggs
env:
  - PLONE=4.1.x
  - PLONE=4.2.x
  - PLONE=4.3.x
